### ISSUE TITLE
Requirements not being installed

### ISSUE THREAD

**Issue by deefrawley** [liberize/Flow.Launcher.Plugin.NumberConverter#1]
Hey liberize,

While this plugin has the code in main.py to look locally for packages, there isn't a workflow action to install those requirements in  /lib before packaging so this plugin just errors out. Have a look [at one of my plugins workflow files](https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert/blob/main/.github/workflows/Publish%20Release.yml) and you should be able to just copy the file and structure into your repo. Then when you commit a PR it will auto run and [ackage correctly.

Cheers,
D

**Comment by liberize** [comment]
pr merged. thanks, and sorry for my late reply.
