### ISSUE TITLE
No way to convert decimal numbers like 10, 1000 to hex, bin etc.

### ISSUE THREAD

**Issue by bharatsonti** [liberize/Flow.Launcher.Plugin.NumberConverter#3]
Current code assumes that, if user enters "10", it is binary format and converts it to hex, dec and oct.
But what if we need hex, bin and oct equivalent of decimal number "10"?
There's no way to do that.

**Possible solution:**
Allow binary numbers to be entered with a prefix "0b". E.g., "0b100"
By default, treat any number without prefix as decimal, even if it contains only 1's and 0's

**Another possible solution**
Add a decimal prefix, something like "0d", e.g, "0d123"
So, if user enters 10, treat it as binary like it's currently treating.
But user enters 0d10, treat it as a decimal and convert it to bin, hex and oct.

**Comment by liberize** [comment]
You are right, I just copied the code from original plugin without noticing this.
I'll take the 0b solution.

**Comment by liberize** [comment]
Fixed. Please try v1.0.2.
